# Generated by Django 3.0.4 on 2020-04-14 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20200414_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/ru/thumb/9/9d/Matrix-DVD.jpg/325px-Matrix-DVD.jpg', max_length=256),
        ),
        migrations.AlterField(
            model_name='film',
            name='text',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
    ]
