# Generated by Django 3.0.4 on 2020-04-07 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20200407_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
