# Generated by Django 3.0.4 on 2020-04-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
