# Generated by Django 3.0.4 on 2020-04-07 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_basket_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='goods_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Goods'),
        ),
    ]
