# Generated by Django 3.0.4 on 2020-04-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_basket_goods_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='goods.Goods'),
        ),
    ]
